<?php

	session_start();
	require __DIR__.'/vendor/autoload.php';

	use Spipu\Html2Pdf\Html2Pdf;
	ob_start();
?>

<style type="text/css">
	table {border-collapse: collapse;}
	table td {padding: 0px}
</style>


	


	<!-- <qrcode value="monPFE" style="width:20mm;background-color: white; color: black;"></qrcode> -->
<!-- <div style="position:absolute;top:2.83in;left:3.04in;width:2.98in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;color:#000000"></span><span style="font-style:normal;font-weight:bold;font-size:11pt;color:#1c1c1c"></span><span style="font-style:normal;font-weight:bold;font-size:11pt;color:#000000"> </span><br/></div> -->
<page>
<!-- <div style="position:absolute;top:11.17in;left:1.82in;width:5.43in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"> </span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"></span>
<span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"> </span><br/></div> -->
<!-- <div style="position:absolute;top:11.33in;left:3.45in;width:2.15in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000">Tel.: 0522 23 06 80 Fax: 0522 23 06 74</span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"> </span><br/></div> -->
<qrcode value="<?=$_SESSION['CNE']?>" style="width:20mm;background-color: white; color: black;"></qrcode>
<img style="position:absolute;top:1.33in;left:3.18in;width:2.66in;height:1.08in" src="ri_1.png" />
<div style="position:absolute;top:4.32in;left:1.51in;width:0.61in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Article 1-</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:4.64in;left:1.51in;width:4.58in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">La présente convention de stage a pour objet de régler les rapports entre:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>

<div style="position:absolute;top:4.96in;left:1.51in;width:5.03in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">La faculté des Sciences Aïn Chock, représentée par le Doyen </span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000">: </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Pr.Omar SADDIQI</span><span style="font-style:normal;font-weight:bold;font-size:9pt;color:#1c1c1c"> </span><br/></div>

<div style="position:absolute;top:5.28in;left:1.51in;width:0.57in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Adresse </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:5.28in;left:2.58in;width:2.70in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">:Km </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">7 Route d’El Jadida Casablanca Maroc</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:5.60in;left:1.51in;width:0.69in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Téléphone:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:5.60in;left:2.58in;width:1.39in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">:+212-5-22-23-06-84</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>

<div style="position:absolute;top:5.92in;left:1.51in;width:0.24in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Fax:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"></span><br/></div>
<div style="position:absolute;top:5.92in;left:2.04in;width:1.39in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">:+212-5-22-23-06-74</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>

<div style="position:absolute;top:6.24in;left:1.51in;width:2.42in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Et désignée ci après par Établissement</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><a href="https://fr.wikipedia.org/wiki/%C3%89tablissement"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"><br><br></span></a>
<a href="https://fr.wikipedia.org/wiki/%C3%89tablissement"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#660099"> </span></a>
<br/></div>
<div style="position:absolute;top:6.56in;left:1.51in;width:3.39in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Et</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">l’Entreprise</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">(ou organisme) </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">ci</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">-dessous</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-color:#000000">mentionnée:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:6.89in;left:1.51in;width:0.79in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Sigle et nom</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:6.89in;left:2.58in;width:3.08in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">:…………………………………………………………………………..</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:7.21in;left:1.51in;width:0.57in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Adresse </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:7.21in;left:2.58in;width:3.12in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">:…………………………………………………………………………..</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:7.53in;left:1.51in;width:4.17in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Représentée par</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> :…………………………………………………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:7.85in;left:1.51in;width:0.69in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Téléphone</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:7.85in;left:2.58in;width:3.12in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">:…………………………………………………………………………..</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"><!-- :………………………………………………………………………….. --></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.17in;left:1.51in;width:3.53in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">E-mail </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">:…………………………………………………………………………..</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.49in;left:1.51in;width:2.26in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Et désignée ci-après par </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">l’Entreprise</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.81in;left:1.51in;width:0.93in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Elle concerne :</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:9.13in;left:1.51in;width:6.03in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Mme/Melle/Mr</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">…………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">..</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">…………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">……</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">étudiant(e) régulièrement </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">inscrit(e) dans l’établissement<br></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:9.33in;left:1.51in;width:5.91in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"><br>pour l’année universitaire 2018</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">-2019, titulaire du  CNE suivant :- </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">……………………,et du CIN……………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-color:#000000">.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;f;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:9.53in;left:1.51in;width:3.54in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:9.85in;left:1.51in;width:2.06in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Et dénommé ci-après </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">le stagiaire</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<img style="position:absolute;top:3.31in;left:1.49in;width:6.02in;height:0.62in" src="ri_2.png" />
<div style="position:absolute;top:3.36in;left:3.50in;width:2.21in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:13pt;color:#000000">CONVENTION DE STAGE</span><span style="font-style:normal;font-weight:normal;font-size:13pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:3.70in;left:3.61in;width:1.94in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;color:#000000">CYCLE MASTER </span><span style="font-style:normal;font-weight:normal;font-size:11pt;color:#000000"> </span><br/></div>


</page>



	<page>
		
		
	
	

<link rel="stylesheet" type="text/css" href="style.css"/>

<!--  <div style="position:absolute;top:2.83in;left:3.04in;width:2.98in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;color:#000000">Faculté des Sciences A</span><span style="font-style:normal;font-weight:bold;font-size:11pt;color:#1c1c1c">ïn Chock-Casablanca</span><span style="font-style:normal;font-weight:bold;font-size:11pt;color:#000000"> </span><br/></div>  -->

<!-- <div style="position:absolute;top:11.17in;left:1.82in;width:5.43in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"> </span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"> </span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"><!-- AïnChock Km 8 Route d’El Jadida B.P 5366 Mâarif Casa 20100 maroc --><!-- </span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"> </span><br/></div> --> 

<!-- <div style="position:absolute;top:11.33in;left:3.45in;width:2.15in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000">Tel.: 0522 23 06 80 Fax: 0522 23 06 74</span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"> </span><br/></div> -->
<img style="position:absolute;top:1.33in;left:3.18in;width:2.66in;height:1.08in" src="ri_3.png" />
<div style="position:absolute;top:3.35in;left:1.51in;width:0.61in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Articl</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">e </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">2-</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:3.67in;left:1.51in;width:3.96in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Il s</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">agit, d</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">un stage qui est prévu dans l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">organisation du Master :</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:3.99in;left:1.51in;width:5.96in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">………………………………………………………………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> et dont</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:4.31in;left:1.51in;width:5.53in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">L</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">accomplissement est nécessaire pour l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">obtention du diplôme du Master par le stagiaire.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:4.63in;left:1.51in;width:0.61in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Articl</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">e </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">3-</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:4.95in;left:1.51in;width:5.43in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Le stage aura lieu d</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">u </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">……………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">.au </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">……………………………………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:5.27in;left:1.51in;width:0.61in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Articl</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">e </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">4-</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<img style="position:absolute;top:5.56in;left:7.23in;width:0.13in;height:0.21in" src="vi_12.png" />
<div style="position:absolute;top:5.61in;left:1.51in;width:5.89in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Pendant toute la période du stage, le stagiaire demeure étudiant de la Faculté des sciences </span><span style="font-style:normal;font-weight:normal;font-size:11pt;;color:#000000">A</span><span style="font-style:normal;font-weight:normal;font-size:11pt;color:#1c1c1c">ïn</span><span style="font-style:normal;font-weight:normal;font-size:11pt;color:#1c1c1c"> </span><br/></div>
<img style="position:absolute;top:5.78in;left:1.51in;width:4.93in;height:0.20in" src="vi_13.png" />
<div style="position:absolute;top:5.82in;left:1.51in;width:4.97in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;color:#1c1c1c">Chock et reste affilé au régime d</span><span style="font-style:normal;font-weight:normal;font-size:11pt;color:#1c1c1c">’</span><span style="font-style:normal;font-weight:normal;font-size:11pt;color:#1c1c1c">assurance contracté durant sa scolarité.</span><span style="font-style:normal;font-weight:normal;font-size:11pt;color:#1c1c1c"> </span><br/></div>
<div style="position:absolute;top:6.16in;left:1.51in;width:0.61in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Articl</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">e </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">5-</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:6.54in;left:1.51in;width:1.29in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Le stage a pour but :</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:6.92in;left:1.75in;width:0.09in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">-</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:6.92in;left:2.02in;width:4.65in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">de</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> permettre à l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">étudiant (e) de prendre contact avec le monde entreprise,</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:7.29in;left:1.75in;width:0.09in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">-</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:7.29in;left:2.02in;width:3.16in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">de tester ses possibilités d</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">adaptation personnelle,</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:7.66in;left:1.75in;width:0.09in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">-</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:7.66in;left:2.02in;width:5.17in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">de mettre en pratique les connaissances qu</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">il a acquises à la faculté des sciences au</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.03in;left:2.02in;width:2.46in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">cours de sa formation du cycle Master .</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.40in;left:1.51in;width:0.61in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Article 6-</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.72in;left:1.51in;width:6.01in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Le projet de stage est intitulé</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">…………………………………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> et son</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:9.04in;left:1.51in;width:4.39in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Programme est établi en fonction de la spécialisation de l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">étudiant (e)</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">. </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:9.36in;left:1.51in;width:5.38in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Dans l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">entreprise, le responsable de stage, chargé du suivi des travaux du stagiaire est :</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:9.68in;left:1.51in;width:5.73in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Mme / Mr </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">…………………………………………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pti;color:#000000"> </span><br/></div>
<div style="position:absolute;top:10.00in;left:1.51in;width:5.72in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Qualité : </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">…………………………………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:10.32in;left:1.51in;width:5.72in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Téléphone : </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">. Fax : </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">………………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:10.65in;left:1.51in;width:5.69in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">E-mail : </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">…………………………………………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>


</page>

	
<page>
	
	
	

<link rel="stylesheet" type="text/css" href="style.css"/>


	

<!-- <div style="position:absolute;top:2.83in;left:3.04in;width:2.98in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;color:#000000"></span><span style="font-style:normal;font-weight:bold;font-size:11pt;color:#1c1c1c"></span><span style="font-style:normal;font-weight:bold;font-size:11pt;color:#000000"> </span><br/></div> -->

<!-- <div style="position:absolute;top:11.17in;left:1.82in;width:5.43in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000">Faculté des Sciences </span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000">–</span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"> </span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-color:#000000"><!-- AïnChock Km 8 Route d’El Jadida B.P 5366 Mâarif Casa 20100 maroc --<!-- ></span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"> </span><br/></div> --> 

<!-- <div style="position:absolute;top:11.33in;left:3.45in;width:2.15in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000">Tel.: 0522 23 06 80 Fax: 0522 23 06 74</span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"> </span><br/></div> -->
<img style="position:absolute;top:1.33in;left:3.18in;width:2.66in;height:1.08in" src="ri_4.png" />
<div style="position:absolute;top:3.67in;left:1.51in;width:5.85in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">A la faculté des sciences, le responsable de stage, chargé du suivi des travaux du stagiai</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">re</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> est : </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:3.99in;left:1.51in;width:5.80in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Mme / Mr </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">……………………………………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">..</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:4.31in;left:1.51in;width:5.80in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Qualité : </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">…………………………………………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">..</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:4.63in;left:1.51in;width:5.79in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Téléphone : </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">……………………………………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">..</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:4.95in;left:1.51in;width:5.80in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">E-mail : </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">……………………………………………………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:5.27in;left:1.51in;width:0.61in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Articl</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">e </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">7-</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:5.59in;left:1.51in;width:5.77in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Le stagiaire doit respecter la discipline et le règlement in</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">té</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">rieur de l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">entreprise qui l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">ei</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">ll</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">e,</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:5.81in;left:1.51in;width:6.02in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">particulièrement </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">en</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> ce qui concerne les horaires de travail et les visites médicales éventuelles. En</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:6.02in;left:1.51in;width:5.86in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">cas de manquement à la discipline, le chef de l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">entreprise se réservera le droit de mettre fin au</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:6.23in;left:1.51in;width:5.21in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">stage de l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">ét</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">udiant stagiaire fautif, après avoir prévenu l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">en</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">seignant visé à l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;;color:#000000">article </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">6.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:6.57in;left:1.51in;width:0.64in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Articl</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">e </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">8-</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:6.89in;left:1.51in;width:4.96in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Le stagiaire n</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">est lié par aucun contrat de travail avec l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">entreprise qui l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">accueille.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;;color:#000000"> </span><br/></div>
<div style="position:absolute;top:7.22in;left:1.51in;width:0.61in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Articl</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">e </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">9-</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:7.54in;left:1.51in;width:4.92in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Le stagiaire ne peut interrompre son stage, sous peine d</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">en perdre de bénéfice.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:7.88in;left:1.51in;width:0.68in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Articl</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">e </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">10</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">-</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.20in;left:1.51in;width:6.03in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">En cas d</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">absence, le stagiaire doit aviser dans les vingt-quatre heures ouvrables le responsable </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.40in;left:1.51in;width:1.80in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">stage au sein de l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">entreprise.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.72in;left:1.51in;width:6.04in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">En cas de difficulté ou d</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">accident, celui-ci est tenu de prendre contact le plus rapidement possible</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.92in;left:1.51in;width:1.33in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">avec l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">établissement.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:9.24in;left:1.51in;width:0.68in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Articl</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">e </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">11</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"></span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:9.56in;left:1.51in;width:6.02in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">L</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">étudiant est soumis à l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">obligation absolue du secret professionnel. En particulier, il ne pourra     </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:9.76in;left:1.51in;width:5.42in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">transmettre à aucun tiers, et sous quelque forme que ce soit, sans l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">accord préalable de</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:9.96in;left:1.51in;width:5.96in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Entreprise, les savoir-faire, documents, résultats d</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">études, dossiers, logiciels, maquettes</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">…</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> dont</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:10.16in;left:1.51in;width:4.55in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">il pourrait avoir connaissance à l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">occasion de son séjour dans l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Entreprise.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>


</page>
<page>
	
	


<link rel="stylesheet" type="text/css" href="style.css"/>



<!-- <div style="position:absolute;top:2.83in;left:3.04in;width:2.98in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;color:#000000"></span><span style="font-style:normal;font-weight:bold;font-size:11pt;color:#1c1c1c"></span><span style="font-style:normal;font-weight:bold;font-size:11pt;color:#000000"> </span><br/></div>
 -->
<!-- <div style="position:absolute;top:11.17in;left:1.82in;width:5.43in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000">Faculté des Sciences </span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000">–</span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"><!-- AïnChock Km 8 Route d’El Jadida B.P 5366 Mâarif Casablanca 20100 Maroc --><!-- </span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"> </span><br/></div>  -->

<!-- <div style="position:absolute;top:11.33in;left:3.45in;width:2.15in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000">Tel.: 0522 23 06 80 Fax: 0522 23 06 74</span><span style="font-style:normal;font-weight:normal;font-size:9pt;color:#000000"> </span><br/></div> -->
<img style="position:absolute;top:1.33in;left:3.18in;width:2.66in;height:1.08in" src="ri_5.png" />
<div style="position:absolute;top:3.35in;left:1.51in;width:0.68in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Articl</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">e </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">12</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">-</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:3.67in;left:1.51in;width:6.12in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Le</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> stagiaire ne peut exiger de rémunération. Cependant l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">entreprise pourra éventuellement             </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:3.87in;left:1.51in;width:5.76in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">contribuer aux dépenses de logement ou de restauration ; mais ceci n</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">est pas une obligation.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:4.19in;left:1.51in;width:5.92in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Par contre les dépenses en relation directe avec son travail dans l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">entreprise, seront supportées</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:4.39in;left:1.51in;width:1.19in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">par cette dernière.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:4.71in;left:1.51in;width:0.68in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Articl</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">e </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">13</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">-</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:5.03in;left:1.51in;width:5.91in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">A la fin du stage le responsable au sein de l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">entreprise fournit une évaluation du comportement</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:5.23in;left:1.51in;width:5.90in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">du stagiaire et de la qualité du travail effectué par celui-ci (fiche d</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">appréciation). Par ailleurs, ce</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:5.43in;left:1.51in;width:5.80in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">stage donne lieu à la rédaction d</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">un rapport que l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">étudiant doit remettre au responsable de la</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:5.63in;left:1.51in;width:5.93in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">formation, après l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">avoir porté </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">à </span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">la connaissance du responsable de stage. Ce rapport peut rester</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:5.83in;left:1.51in;width:5.71in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">la propriété de l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">entreprise dans le cas de sauvegarde du secret industriel ; il sera cependant</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:6.03in;left:1.51in;width:5.75in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">communiqué, par une soutenance orale devant un jury composé des encadrants mentionnés</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:6.23in;left:1.51in;width:3.26in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">dans l</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">article 6 plus les membres du jury de la filière.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:6.87in;left:5.71in;width:1.84in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">Casablanca :</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000">…………………………</span><span style="font-style:normal;font-weight:normal;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.48in;left:1.83in;width:0.75in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Le stagiaire</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.48in;left:2.96in;width:1.25in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Le Représentant de</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.67in;left:3.21in;width:0.76in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">l</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">’</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">entreprise</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.48in;left:4.70in;width:1.22in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Encadrant/Chef </span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.67in;left:4.37in;width:1.89in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">département/Coordonnateur</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.85in;left:4.94in;width:0.74in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">de la filière</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<div style="position:absolute;top:8.48in;left:6.68in;width:0.62in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000">Le Doyen</span><span style="font-style:normal;font-weight:bold;font-size:10pt;color:#000000"> </span><br/></div>
<img style="position:absolute;top:8.44in;left:1.51in;width:0.01in;height:0.01in" src="vi_20.png" />
<img style="position:absolute;top:8.44in;left:1.51in;width:0.01in;height:0.01in" src="vi_21.png" />
<img style="position:absolute;top:8.44in;left:1.51in;width:1.35in;height:0.01in" src="vi_22.png" />
<img style="position:absolute;top:8.44in;left:2.86in;width:0.01in;height:0.01in" src="vi_23.png" />
<img style="position:absolute;top:8.44in;left:2.87in;width:1.41in;height:0.01in" src="vi_24.png" />
<img style="position:absolute;top:8.44in;left:4.28in;width:0.01in;height:0.01in" src="vi_25.png" />
<img style="position:absolute;top:8.44in;left:4.29in;width:2.02in;height:0.01in" src="vi_26.png" />
<img style="position:absolute;top:8.44in;left:6.30in;width:0.01in;height:0.01in" src="vi_27.png" />
<img style="position:absolute;top:8.44in;left:6.31in;width:1.32in;height:0.01in" src="vi_28.png" />
<img style="position:absolute;top:8.44in;left:7.63in;width:0.01in;height:0.01in" src="vi_29.png" />
<img style="position:absolute;top:8.44in;left:7.63in;width:0.01in;height:0.01in" src="vi_30.png" />
<img style="position:absolute;top:8.45in;left:1.51in;width:0.01in;height:0.75in" src="vi_31.png" />
<img style="position:absolute;top:8.45in;left:2.86in;width:0.01in;height:0.75in" src="vi_32.png" />
<img style="position:absolute;top:8.45in;left:4.28in;width:0.01in;height:0.75in" src="vi_33.png" />
<img style="position:absolute;top:8.45in;left:6.30in;width:0.01in;height:0.75in" src="vi_34.png" />
<img style="position:absolute;top:8.45in;left:7.63in;width:0.01in;height:0.75in" src="vi_35.png" />
<img style="position:absolute;top:9.20in;left:1.51in;width:0.01in;height:0.01in" src="vi_36.png" />
<img style="position:absolute;top:9.20in;left:1.51in;width:1.35in;height:0.01in" src="vi_37.png" />
<img style="position:absolute;top:9.20in;left:2.86in;width:0.01in;height:0.01in" src="vi_38.png" />
<img style="position:absolute;top:9.20in;left:2.87in;width:1.41in;height:0.01in" src="vi_39.png" />
<img style="position:absolute;top:9.20in;left:4.28in;width:0.01in;height:0.01in" src="vi_40.png" />
<img style="position:absolute;top:9.20in;left:4.29in;width:2.02in;height:0.01in" src="vi_41.png" />
<img style="position:absolute;top:9.20in;left:6.30in;width:0.01in;height:0.01in" src="vi_42.png" />
<img style="position:absolute;top:9.20in;left:6.31in;width:1.32in;height:0.01in" src="vi_43.png" />
<img style="position:absolute;top:9.20in;left:7.63in;width:0.01in;height:0.01in" src="vi_44.png" />
<img style="position:absolute;top:9.21in;left:1.51in;width:0.01in;height:1.25in" src="vi_45.png" />
<img style="position:absolute;top:10.46in;left:1.51in;width:0.01in;height:0.01in" src="vi_46.png" />
<img style="position:absolute;top:10.46in;left:1.51in;width:0.01in;height:0.01in" src="vi_47.png" />
<img style="position:absolute;top:10.46in;left:1.51in;width:1.35in;height:0.01in" src="vi_48.png" />
<img style="position:absolute;top:9.21in;left:2.86in;width:0.01in;height:1.25in" src="vi_49.png" />
<img style="position:absolute;top:10.46in;left:2.86in;width:0.01in;height:0.01in" src="vi_50.png" />
<img style="position:absolute;top:10.46in;left:2.87in;width:1.41in;height:0.01in" src="vi_51.png" />
<img style="position:absolute;top:9.21in;left:4.28in;width:0.01in;height:1.25in" src="vi_52.png" />
<img style="position:absolute;top:10.46in;left:4.28in;width:0.01in;height:0.01in" src="vi_53.png" />
<img style="position:absolute;top:10.46in;left:4.29in;width:2.02in;height:0.01in" src="vi_54.png" />
<img style="position:absolute;top:9.21in;left:6.30in;width:0.01in;height:1.25in" src="vi_55.png" />
<img style="position:absolute;top:10.46in;left:6.30in;width:0.01in;height:0.01in" src="vi_56.png" />
<img style="position:absolute;top:10.46in;left:6.31in;width:1.32in;height:0.01in" src="vi_57.png" />
<img style="position:absolute;top:9.21in;left:7.63in;width:0.01in;height:1.25in" src="vi_58.png" />
<img style="position:absolute;top:10.46in;left:7.63in;width:0.01in;height:0.01in" src="vi_59.png" />
<img style="position:absolute;top:10.46in;left:7.63in;width:0.01in;height:0.01in" src="vi_60.png" />



</page>

<?php
	$content =ob_get_clean();

	$html2pdf = new HTML2PDF('P', 'A4', 'en');
	$html2pdf->pdf->SetDisplayMode('fullpage');
	$html2pdf->writeHTML($content);
	$html2pdf->Output('conventionDeStage.pdf');
?>
